# This is a Docker Compose configuration
# intended for development purposes only

version: '3'

volumes:
  db: {}

services:
  db:
    container_name: bookstack-db
    image: postgres
    environment:
      POSTGRES_DB: bookstackapp
      POSTGRES_USER: bookstack-test
      POSTGRES_PASSWORD: bookstack-test
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/bookstack/postgresql/data:/var/lib/postgresql/data
  app:
    container_name: bookstack-app
    build:
      context: .
      dockerfile: ./dev/docker/Dockerfile
    environment:
      APP_URL: http://localhost:${DEV_PORT:-8080}
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: bookstackapp
      DB_USERNAME: bookstack-test
      DB_PASSWORD: bookstack-test
      MAIL_DRIVER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
    ports:
      - ${DEV_PORT:-8080}:80
    volumes:
      - ./:/app
      - ./dev/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint: /app/dev/docker/entrypoint.app.sh
    extra_hosts:
    - "host.docker.internal:host-gateway"
  node:
    container_name: bookstack-node
    image: node:alpine
    working_dir: /app
    user: node
    volumes:
      - ./:/app
    entrypoint: /app/dev/docker/entrypoint.node.sh
  mailhog:
    container_name: bookstack-mailhog
    image: mailhog/mailhog
    ports:
      - ${DEV_MAIL_PORT:-8025}:8025
